import type { Metadata } from "next";
import '../css/global.scss';
import 'bootstrap/dist/css/bootstrap.min.css';
import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Nav />
        <div className="wrapper">
          {children}
        </div>
      </body>
    </html>
  );
}
